// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4VhuhtrMPK98mq0UuPpg-9Zk4uwe1zrU',
    appId: '1:388852557650:web:dd90c8941d9520270efc8b',
    messagingSenderId: '388852557650',
    projectId: 'jersey-drip-61cc0',
    authDomain: 'jersey-drip-61cc0.firebaseapp.com',
    storageBucket: 'jersey-drip-61cc0.firebasestorage.app',
    measurementId: 'G-RYFPYK9PML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf5DGTzhT02tW7fF5N9B_qZWvrYKOe8Sg',
    appId: '1:388852557650:android:dcf0aae5c13bbc3e0efc8b',
    messagingSenderId: '388852557650',
    projectId: 'jersey-drip-61cc0',
    storageBucket: 'jersey-drip-61cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDafuwMN1lokk_sRa9jVROWrMstYiG6SY',
    appId: '1:388852557650:ios:2ea01f0f8a6864040efc8b',
    messagingSenderId: '388852557650',
    projectId: 'jersey-drip-61cc0',
    storageBucket: 'jersey-drip-61cc0.firebasestorage.app',
    iosClientId: '388852557650-1j6akqf9qoft5iu32st67rdeifjkc6tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jerseyapp',
  );
}
